version: '3'
services:
  neo4j:
    image: neo4j:3.4
    hostname: neo4j
    container_name: neo4j
    ports:
    - "7474:7474"
    - "7687:7687"
    depends_on:
    - kafka
    volumes:
    - "<DIRECTORY OF neo4j-streams-3.4.1.jar>:<DIRECTORY PLUGINS IN DOCKER>"
    environment:
      NEO4J_AUTH: neo4j/PASSWORD
      NEO4J_dbms_logs_debug_level: DEBUG
      # KAFKA related configuration
      NEO4J_kafka_zookeeper_connect: zookeeper:12181
      NEO4J_kafka_bootstrap_servers: kafka:19092
      NEO4J_kafka_auto_offset_reset: earliest 
      NEO4J_kafka_group_id: neo4j
      NEO4J_streams_sink_topic_cypher_neo4j: "MERGE (t:Tweet{text: event.text}) MERGE (u:User{name: event.user_name}) MERGE (t)-[:BELONGS_TO]->(u)" 
      #Query need to be adjusted, this is just a dummy example
      NEO4J_streams_sink_polling_interval: 1000  
      NEO4J_streams_sink_enable: "true" 
      NEO4J_streams_procedures_enable: "true"

  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
    - "12181:12181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 12181

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
    - "19092:19092"
    depends_on:
    - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092
